# Generated by Django 3.2.5 on 2021-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_question_gung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gung',
            field=models.CharField(default='경복궁', max_length=40),
        ),
    ]
